//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Amenity
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="You must provide a name for the service/amenity.")]
        [Display(Name ="Service/Amenity Name")]
        [MaxLength (50, ErrorMessage ="Amenity name must not exceed 50 characters") ]
        public string Amenity_Name { get; set; }
        
        public List<Amenity> AmenityList { get; set;}
        [Required(ErrorMessage ="You must select the building this service is located in.")]
        [Display(Name ="Building")]
        public int Building_id { get; set; }
      
        public virtual Building Building { get; set; }
    }
}
