//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Building
    {
        public Building()
        {
            this.Amenities = new HashSet<Amenity>();
            this.Entrances = new HashSet<Entrance>();
            this.ParkingLots = new HashSet<ParkingLot>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="You must provide a name for the building.")]
        [Display(Name ="Building Name")]
        [MaxLength( 50, ErrorMessage ="Building name cannot exceed 50 characters")]
        public string Building_Name { get; set; }
    
        public virtual ICollection<Amenity> Amenities { get; set; }
        public virtual ICollection<Entrance> Entrances { get; set; }
        public virtual ICollection<ParkingLot> ParkingLots { get; set; }
    }
}
