//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmergencyPatient
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="You must enter a first name.")]
        [Display(Name="First Name")]
        [MaxLength (25, ErrorMessage ="First name cannot exceed 25 characters")]
        public string First_Name { get; set; }
        [Required(ErrorMessage ="You must enter a last name")]
        [Display(Name ="Last Name")]
        [MaxLength (25, ErrorMessage ="Last name cannot exceed 25 characters")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage ="You must enter a value for the health card number")]
        [RegularExpression(@"^[1-9]{9}[a-z|A-Z]{2}$", ErrorMessage ="Invalid health card format.")]
        [Display(Name ="Health Card Number")]
        public string Card_Number { get; set; }
        public int Severity { get; set; }
        [Display(Name ="Check in Date/Time")]
        public System.DateTime Checkin { get; set; }
    }
}
