//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmergencyDoctor
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="You must enter a first name for the doctor")]
        [Display(Name ="First name")]
        [MaxLength (25, ErrorMessage ="First name cannot exceed 25 letters")]
        public string First_Name { get; set; }
        [Required(ErrorMessage ="You must enter a last name for the doctor")]
        [Display(Name = "Last Name")]
        [MaxLength (25, ErrorMessage ="Last name cannot exceed 25 letters")]
        public string Last_Name { get; set; }
        [Display(Name ="On Duty?")]
        public string OnDuty { get; set; }
    }
}
