//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Entrance
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="You must provide a name for this entrance")]
        [Display(Name ="Entrance Name")]
        [MaxLength (50, ErrorMessage ="Entrance name cannot exceed 50 characters")]
        public string Entrance_Name { get; set; }
        [Required(ErrorMessage ="You must provide a building for this entrance")]
        [Display(Name ="Building")]
        public int Building_id { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
