//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class News
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="You must provide a title for the page")]
        [MaxLength(35, ErrorMessage ="Limit of 35 characters")]
        public string Title { get; set; }
        [Required(ErrorMessage ="You must provide a short blurb for the article")]
        [MaxLength(ErrorMessage ="Limit of 45 characters")]
        public string Blurb { get; set; }
        public System.DateTime Date { get; set; }
        public int Priority { get; set; }
        public string Photo { get; set; }
        [AllowHtml]
        [Required(ErrorMessage ="You must provide content for the page")]
        public string Content { get; set; }
    }
}
