//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ParkingLot
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="You must provide a name for the parking lot")]
        [Display(Name ="Parking Lot Name")]
        [MaxLength (50, ErrorMessage ="Parking Lot name must not exceed 50 characters")]
        public string Lot_Name { get; set; }
        [Required(ErrorMessage ="You must specify the closest building")]
        [Display(Name ="Closest Building")]
        public int Building_id { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
