//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PastPatient
    {
        public int Id { get; set; }
        [Display(Name ="First Name")]
        public string First_Name { get; set; }
        [Display(Name ="Last Name")]
        public string Last_Name { get; set; }
        [Display(Name ="Health Card Number")]
        public string Card_Number { get; set; }
        public int Severity { get; set; }
        [Display(Name ="Date/Time Checked In")]
        public System.DateTime Checkin { get; set; }
    }
}
